/**
 * Manual type declarations for Cloudflare Workers secrets.
 *
 * Secrets are set via `wrangler secret put` and are NOT generated by
 * `wrangler types` (by design — they have no value in wrangler.jsonc).
 * Declare them here so TypeScript knows they exist on the Env interface.
 *
 * Local dev: add the same keys to backend/.dev.vars (gitignored).
 */
declare namespace Cloudflare {
  interface Env {
    ADMIN_API_KEY: string;
  }
}
